CREATE TABLE public.merchants (
	id SERIAL PRIMARY KEY,
	code VARCHAR(10) UNIQUE NOT NULL,
	"name" VARCHAR(100) UNIQUE NOT NULL,
    area_id INTEGER REFERENCES areas(id) NOT NULL,
    "address" TEXT NOT NULL,
    "type" VARCHAR(2) NOT NULL,
    "is_open" BOOLEAN DEFAULT false NOT NULL,
    open_days VARCHAR(100) NOT NULL,
    close_days VARCHAR(100) NOT NULL,
    open_hours TIME NOT NULL,
    close_hours TIME NOT NULL,
    owner_name VARCHAR(100) NOT NULL,
    owner_nik VARCHAR(100) NULL,
    owner_npwp VARCHAR(100) NULL,
    head_name VARCHAR(100) NOT NULL,
    head_nik VARCHAR(100) NULL,
    head_npwp VARCHAR(100) NULL,
    bank_account VARCHAR(100) NOT NULL,
    bank_name VARCHAR(100) NOT NULL,
    img TEXT NULL,
	"status" BOOLEAN DEFAULT false NOT NULL,
	created_date TIMESTAMPTZ(0) NOT NULL,
    created_by VARCHAR(10) NOT NULL,
	updated_date TIMESTAMPTZ(0) NULL,
    updated_by VARCHAR(10) NULL,
	deleted_date TIMESTAMPTZ(0) NULL,
    deleted_by VARCHAR(10) NULL,
    "version" INTEGER NOT NULL
);

COMMENT ON COLUMN public.merchants.type is 'M = Manual, SA = Semi Auto, FA = Full Auto';